#!/usr/bin/env python3
"""Generate override CSS from a measured computed-style diff.

Inputs: two captures (src = Moderno/Elementor reference at 1920px, dst = Bricks
port at 1920px), one line per element:
  id|display|flexDir|justify|align|w|h|position|alignSelf|order|gap|mT,mR,mB,mL|pT,pR,pB,pL|textAlign|flexGrow|minHeight
Elements hidden at capture time are `id|none`.

For every element present in BOTH captures, emit only the properties that
differ. Widths are emitted in vw (source measured at 1920) and only for flex
containers whose width diverges >40px — text/widget blocks keep natural size.
Desktop-only overrides: wrapped in @media (min-width:1025px) so the port CSS's
own responsive rules keep governing tablet/mobile.

Output appended target: bricks-child/moderno-live-diff.css (enqueued by child).
Rerunnable: python3 generate-live-diff.py <src.txt> <dst.txt>
"""
import sys
from pathlib import Path

OUT = "/Users/bam/Local Sites/tsc-beta/app/public/wp-content/themes/bricks-child/moderno-live-diff.css"  # overridable via argv[3]
FIELDS = ["display", "dir", "justify", "align", "w", "h", "pos", "self", "order",
          "gap", "margin", "padding", "ta", "grow", "minh"]


def parse(path):
    rows = {}
    for line in Path(path).read_text().splitlines():
        parts = line.strip().split("|")
        if len(parts) < 2:
            continue
        if parts[1] == "none":
            rows[parts[0]] = None
        else:
            rows[parts[0]] = dict(zip(FIELDS, parts[1:]))
    return rows


def vw(px):
    return f"{float(px) / 19.2:.2f}vw"


# Widgets whose el- node in Bricks is the VISUAL element itself (button anchors):
# wrapper-level diffs (display:block, padding:0) would crush their real styling,
# which lives in bricks-child style.css measured from a.c-button on the reference.
SKIP_IDS = {"63a81bf", "2ff5950", "084d34c", "83ace67", "4d297e5", "0e291aa"}


def main():
    global OUT
    if len(sys.argv) > 3:
        OUT = sys.argv[3]
    prefix = sys.argv[4] if len(sys.argv) > 4 else ""
    src = parse(sys.argv[1] if len(sys.argv) > 1 else "src.txt")
    dst = parse(sys.argv[2] if len(sys.argv) > 2 else "dst.txt")
    rules = []
    for eid, s in src.items():
        if eid in SKIP_IDS:
            continue
        d = dst.get(eid)
        if s is None or d is None:
            continue
        decl = []
        if s["display"] != d["display"]:
            decl.append(f"display:{s['display']}")
        if s["display"] == "flex":
            if s["dir"] != d["dir"]:
                decl.append(f"flex-direction:{s['dir']}")
            for key, prop in (("justify", "justify-content"), ("align", "align-items")):
                if s[key] != d[key] and s[key] != "normal":
                    decl.append(f"{prop}:{s[key]}")
                elif s[key] == "normal" and d[key] not in ("normal", "stretch"):
                    decl.append(f"{prop}:normal")
            sgap = s["gap"] if s["gap"] != "normal" else "0px"
            dgap = d["gap"] if d["gap"] != "normal" else "0px"
            if sgap != dgap:
                decl.append(f"gap:{sgap}")
            if abs(float(s["w"]) - float(d["w"])) > 40:
                decl.append(f"width:{vw(s['w'])}")
                decl.append("max-width:100%")
        if s["self"] != d["self"]:
            decl.append(f"align-self:{s['self']}")
        if s["order"] != d["order"]:
            decl.append(f"order:{s['order']}")
        if s["grow"] != d["grow"]:
            decl.append(f"flex-grow:{s['grow']}")
        if s["ta"] != d["ta"]:
            decl.append(f"text-align:{s['ta']}")
        if s["pos"] != d["pos"] and s["pos"] != "static":
            decl.append(f"position:{s['pos']}")
        if s["margin"] != d["margin"]:
            mt, mr, mb, ml = s["margin"].split(",")
            decl.append(f"margin:{mt} {mr} {mb} {ml}")
        if s["padding"] != d["padding"]:
            pt, pr, pb, pl = s["padding"].split(",")
            decl.append(f"padding:{pt} {pr} {pb} {pl}")
        if s["minh"] != d["minh"] and s["minh"] != "auto":
            decl.append(f"min-height:{s['minh']}")
        if decl:
            # doubled class beats the port-css shim's [class*="el-"].brxe-* selectors (0,2,0)
            rules.append(f"{prefix}.el-{eid}.el-{eid}{{{';'.join(decl)}}}")
    css = ("/* moderno-live-diff.css — GENERATED by generate-live-diff.py.\n"
           "   Measured computed-style diff: Moderno reference (localhost:10025)\n"
           "   vs Bricks port, both at 1920px. Desktop-scoped. DO NOT hand-edit. */\n"
           "@media (min-width:1025px){\n" + "\n".join(rules) + "\n}\n")
    Path(OUT).write_text(css)
    print(f"wrote {OUT}: {len(rules)} element overrides")


if __name__ == "__main__":
    main()
