#!/usr/bin/env python3
"""Port ideapark widgets 1:1 from the live Moderno reference into the Bricks site.

Two jobs:
1. CSS: extract every rule for the ideapark component classes (c-ip-banners,
   c-ip-news/news, c-ip-social, swiper) from the reference's combined stylesheet
   into bricks-child/moderno-components.css (media queries preserved).
2. HTML: pull each target widget's rendered fragment from the reference
   homepage HTML, rewrite reference URLs to the local site, and replace the
   converter's hidden placeholder blocks inside _bricks_page_content_2 with
   Bricks text-basic elements carrying that exact HTML.

Deterministic + rerunnable. Reference must be up at SRC_URL.
"""
import re
import subprocess
import sys
import urllib.request
from pathlib import Path

SRC_URL = "http://localhost:10025"
DST_URL = "http://localhost:10009"
COMBINED = "/private/tmp/claude-501/-Users-bam-Library-CloudStorage-GoogleDrive-we-therum-studio-My-Drive-Therum-Projects-TSC-BETA/f39b8ece-7f47-4ca7-9b74-38aa7b85aa50/scratchpad/combined.css"
OUT_CSS = "/Users/bam/Local Sites/tsc-beta/app/public/wp-content/themes/bricks-child/moderno-components.css"
CLASS_HINTS = ("c-ip-banners", "c-ip-news", "c-news", "c-ip-social", "swiper")

MYSQL = "/Users/bam/Library/Application Support/Local/lightning-services/mysql-8.4.0/bin/darwin-arm64/bin/mysql"
SOCK = "/Users/bam/Library/Application Support/Local/run/aMNHd3PFU/mysql/mysqld.sock"
PHP_GLOB = "/Users/bam/Library/Application Support/Local/lightning-services/php-8.5*/bin/darwin-arm64/bin/php"

# elementor-id -> widget we port verbatim
TARGET_IDS = ["9bb4e1d", "50c6c5e", "0956f3a", "24b22ca"]
PAGE_ID = 165012


def split_rules(css: str):
    """Yield (media_prefix, selector, body) for every top-level and @media rule."""
    i, n = 0, len(css)
    media = ""
    stack_end = -1
    while i < n:
        if css.startswith("@media", i):
            b = css.index("{", i)
            media = css[i:b].strip()
            stack_end = _match_brace(css, b)
            i = b + 1
            continue
        if stack_end != -1 and i >= stack_end:
            media = ""
            stack_end = -1
            i += 1
            continue
        j = css.find("{", i)
        if j == -1:
            break
        k = _match_brace(css, j)
        sel = css[i:j].strip()
        if sel.startswith("@"):
            i = k + 1
            continue
        yield media, sel, css[j + 1:k]
        i = k + 1


def _match_brace(css, open_idx):
    depth = 0
    for i in range(open_idx, len(css)):
        if css[i] == "{":
            depth += 1
        elif css[i] == "}":
            depth -= 1
            if depth == 0:
                return i
    return len(css)


def extract_css():
    css = Path(COMBINED).read_text()
    plain, medias = [], {}
    for media, sel, body in split_rules(css):
        if any(h in sel for h in CLASS_HINTS):
            if media:
                medias.setdefault(media, []).append(f"{sel}{{{body}}}")
            else:
                plain.append(f"{sel}{{{body}}}")
    parts = ["/* GENERATED by port-ideapark-widgets.py — ideapark component CSS from the\n   live Moderno reference combined stylesheet. DO NOT hand-edit. */"]
    parts += plain
    for media, rules in medias.items():
        parts.append(media + "{" + "".join(rules) + "}")
    out = "\n".join(parts).replace(SRC_URL, DST_URL)
    Path(OUT_CSS).write_text(out)
    print(f"css: {len(plain)} rules + {len(medias)} media blocks -> {OUT_CSS}")


def fetch_fragments():
    html = urllib.request.urlopen(SRC_URL + "/", timeout=15).read().decode()
    frags = {}
    for eid in TARGET_IDS:
        m = re.search(r'data-id="' + eid + r'"', html)
        if not m:
            print(f"frag {eid}: NOT FOUND")
            continue
        start = html.rfind("<div", 0, m.start())
        i, depth = start, 0
        for tag in re.finditer(r"<div\b|</div>", html[start:]):
            depth += 1 if tag.group().startswith("<div") else -1
            if depth == 0:
                i = start + tag.end()
                break
        frag = html[start:i]
        inner = re.search(r'<div class="elementor-widget-container">(.*)</div>\s*$', frag, re.S)
        frag = inner.group(1) if inner else frag
        frag = frag.replace(SRC_URL, DST_URL).replace(' loading="lazy"', "")
        # LiteSpeed lazy-load: real URLs sit in data-src/data-srcset; src is an
        # inline SVG placeholder. Promote the real attributes.
        frag = re.sub(r'src="data:image/svg\+xml;base64,[^"]*"', "", frag)
        frag = frag.replace("data-src=", "src=").replace("data-srcset=", "srcset=")
        frag = frag.replace(' data-lazyloaded="1"', "")
        frags[eid] = frag
        print(f"frag {eid}: {len(frag)} bytes")
    return frags


def patch_meta(frags):
    import glob
    php = sorted(glob.glob(PHP_GLOB))[0]
    ser = subprocess.run([MYSQL, "-S", SOCK, "-u", "root", "-proot", "-N", "--raw", "-e",
                          f"SELECT meta_value FROM local.smxxpostmeta WHERE post_id={PAGE_ID} AND meta_key='_bricks_page_content_2'"],
                         capture_output=True, text=True).stdout
    Path("/tmp/brx-patch-in.ser").write_text(ser.rstrip("\n"))
    import json
    Path("/tmp/brx-frags.json").write_text(json.dumps(frags))
    php_code = r'''
$els = unserialize(trim(file_get_contents("/tmp/brx-patch-in.ser")));
$frags = json_decode(file_get_contents("/tmp/brx-frags.json"), true);
$patched = 0;
foreach ($els as &$el) {
    $cls = $el["settings"]["_cssClasses"] ?? "";
    foreach ($frags as $eid => $html) {
        if (strpos($cls, "el-" . $eid) !== false) {
            $el["name"] = "text-basic";
            $el["settings"] = [
                "text" => $html,
                "_cssClasses" => "ideapark-ported el-" . $eid,
            ];
            $el["children"] = [];
            $patched++;
        }
    }
}
unset($el);
file_put_contents("/tmp/brx-patch-out.ser", serialize($els));
echo "patched: $patched\n";
'''
    Path("/tmp/brx-patch.php").write_text("<?php\n" + php_code)
    print(subprocess.run([php, "/tmp/brx-patch.php"], capture_output=True, text=True).stdout.strip())
    subprocess.run([MYSQL, "-S", SOCK, "-u", "root", "-proot", "local"],
                   input=f"UPDATE smxxpostmeta SET meta_value = LOAD_FILE('/tmp/brx-patch-out.ser') WHERE post_id={PAGE_ID} AND meta_key='_bricks_page_content_2';",
                   capture_output=True, text=True)
    # LOAD_FILE often blocked; verify and fall back to hex literal
    chk = subprocess.run([MYSQL, "-S", SOCK, "-u", "root", "-proot", "-N", "-e",
                          f"SELECT LENGTH(meta_value) FROM local.smxxpostmeta WHERE post_id={PAGE_ID} AND meta_key='_bricks_page_content_2'"],
                         capture_output=True, text=True).stdout.strip()
    want = len(Path("/tmp/brx-patch-out.ser").read_bytes())
    if chk != str(want):
        hexv = Path("/tmp/brx-patch-out.ser").read_bytes().hex()
        sql = f"UPDATE smxxpostmeta SET meta_value = UNHEX('{hexv}') WHERE post_id={PAGE_ID} AND meta_key='_bricks_page_content_2';"
        Path("/tmp/brx-patch.sql").write_text(sql)
        subprocess.run(f'"{MYSQL}" -S "{SOCK}" -u root -proot local < /tmp/brx-patch.sql', shell=True)
        chk = subprocess.run([MYSQL, "-S", SOCK, "-u", "root", "-proot", "-N", "-e",
                              f"SELECT LENGTH(meta_value) FROM local.smxxpostmeta WHERE post_id={PAGE_ID} AND meta_key='_bricks_page_content_2'"],
                             capture_output=True, text=True).stdout.strip()
    print(f"meta length now {chk} (want {want})")


OUT_INSTANCE = "/Users/bam/Local Sites/tsc-beta/app/public/wp-content/themes/bricks-child/moderno-instance.css"


def extract_instance_css():
    """The reference's LiteSpeed bundle holds the TRUE per-instance Elementor
    rules (built when the cache was warm) — richer than the regenerated
    uploads/elementor/css files. Keep every rule that targets .elementor-*,
    translate selectors to el- hooks."""
    css = Path(COMBINED).read_text()
    def translate_sel(sel):
        sel = re.sub(r"\.elementor-element\.elementor-element-([0-9a-f]+)", r".el-\1", sel)
        sel = re.sub(r"\.elementor-element-([0-9a-f]+)", r".el-\1", sel)
        sel = re.sub(r"\.elementor-\d+\s+", "", sel)
        sel = re.sub(r"\.elementor-kit-\d+", ":root", sel)
        sel = re.sub(r"(\.el-[0-9a-f]+)\.elementor-element", r"\1", sel)
        for inner in (r"\s*>\s*\.elementor-widget-container", r"\s+\.elementor-widget-container",
                      r"\s*>\s*\.elementor-container", r"\s+\.elementor-container",
                      r"\s+\.elementor-widget-wrap", r"\s+\.elementor-heading-title",
                      r"\s+\.elementor-button", r"\s+\.elementor-text-editor"):
            sel = re.sub(inner, "", sel)
        return sel
    plain, medias = [], {}
    for media, sel, body in split_rules(css):
        if "elementor" not in sel:
            continue
        tsel = translate_sel(sel)
        if "elementor" in tsel:  # structural leftovers we can't map — skip
            continue
        rule = f"{tsel}{{{body}}}"
        if media:
            medias.setdefault(media, []).append(rule)
        else:
            plain.append(rule)
    parts = ["/* GENERATED by port-ideapark-widgets.py (extract_instance_css) — per-instance\n   Elementor rules recovered from the reference LiteSpeed bundle. DO NOT hand-edit. */"]
    parts += plain
    for media, rules in medias.items():
        parts.append(media + "{" + "".join(rules) + "}")
    out = "\n".join(parts).replace(SRC_URL, DST_URL)
    Path(OUT_INSTANCE).write_text(out)
    print(f"instance css: {len(plain)} rules + {len(medias)} media blocks -> {OUT_INSTANCE}")


if __name__ == "__main__":
    extract_css()
    extract_instance_css()
    frags = fetch_fragments()
    if frags:
        patch_meta(frags)
